[default.probe]
# default to STLink V2-1 probe
usb_vid = "0483"
usb_pid = "374b"
protocol = "Swd"
speed = 1800

[default.flashing]
enabled = true
restore_unwritten_bytes = true
do_chip_erase = false

[default.general]
chip = "ATSAMD21E17A"

[default.rtt]
enabled = false
show_timestamps = true
timeout = 3000
